# This scripts builds a ground truth dataset using the checkpoint dataset

import sys
import logging
import pandas as pd

from google.cloud import bigquery

from scripts import (
    BIGQUERY_PROJECT as PROJECT_ID,
    BIGQUERY_DATASET as DATASET_ID,
    GOOGLE_CLOUD_BUCKET as GCP_BUCKET,
)
from scripts.gcp import (
    process_bigquery,
    check_bigquery_table_exists,
    dump_bigquery_table,
    read_gzipped_json_from_blob,
)


CHECKPOINT_REPOS = sorted(
    set(
        """
armoly/Discord-Bot
armoly/Ds-Spm
armoly/Email-Spm
armoly/Tg-Spm
armoly/Tg-SpmTg-Spm
armoly/Twt-Spm
bleblquck/FT-Vieww
bleblquck/Kck-Vw
bleblquck/Trv-Vws
bleblquck/Tw-Vws
dscvm/Discord-Vbot
dscvm/Visoul-Grabber
glassmuysa/Htlx-Gen-Check
glassmuysa/Mail-Ac-Gen
glassmuysa/TwT-Genr
glassmuysa/Ytb-Dwnld
gooles54/Rison-Raid-Bot
gooles54/Rison-Trading-Bot
gooles54/WPscn
lzero121/TWT-vWS
lzero121/Ytb-Vws
lzero121/iNS-vWS
lzero121/tK-vWS
memekch/TWT-vWS
memekch/Ytb-Vws
memekch/iNS-vWS
memekch/tK-vWS
memo1l/ChatGpt-Turbo
sokratso/KMSpic-Ac
valiso0/Mail-Ac-Generator
valiso0/TwT-Gen
valiso0/Ytb-Dwnld
merHashima/Voicemod-2024-Crack-Full-Version
Danms661/NEAR-HOT-WALLET-AUTOBOT
Danms661/SEED-SEARCHER-Crypto-Checker-30-Wallets
Danms661/Top-Osu-Hacks-2024-Aim-Assist-Bots-and-More
Essence-Of-Slimez-37/Pinnacle-Studio-Crack
Essence-Of-Slimez-37/Pro-Tools-Crack
Essence-Of-Slimez-37/ProtonVPN-Free-Crack-2024
Essence-Of-Slimez-37/ReiBoot-Pro-Crack-Download-Free
Essence-Of-Slimez-37/Revit-Crack
Essence-Of-Slimez-37/Rhinoceros-Crack
Essence-Of-Slimez-37/RisePro-Stealer-HVNC-Crack
Essence-Of-Slimez-37/SEED-SEARCHER-Crypto-Checker-30-Wallets
Essence-Of-Slimez-37/Simple-Checker-Crack
Essence-Of-Slimez-37/Snapster-autobot
Essence-Of-Slimez-37/SolidWorks-crack
Essence-Of-Slimez-37/Sound-Forge-crack
Essence-Of-Slimez-37/Steam-account-autoregger-creation-of-maFile
Essence-Of-Slimez-37/Sublime-Text-crack
Essence-Of-Slimez-37/TFT-Unlocker-Tool-FUll
Essence-Of-Slimez-37/TeamViewer-Latest-Crack-2024
Essence-Of-Slimez-37/The-unifier-is-both-Video
Essence-Of-Slimez-37/Toon-Boom-Harmony-Crack
Essence-Of-Slimez-37/Top-Osu-Hacks-2024-Aim-Assist-Bots-and-More
Essence-Of-Slimez-37/Unity-Pro-Cracks
Essence-Of-Slimez-37/VLC-Media-Player-Crack
Essence-Of-Slimez-37/Vape-V4-Crack-Kangaroo
Essence-Of-Slimez-37/Voicemod-2024-Crack-Full-Version
Essence-Of-Slimez-37/Youtube-365-Auto-upload-cheat-checker
Essence-Of-Slimez-37/ZBrush-Crack
Essence-Of-Slimez-37/pixel-wallet-bot-free
Essence-Of-Slimez-37/yescoin-bot-installation
HeangHorn/Corel-Draw-Free-Crack-2024
Knight-JNXU/Catizen-Auto-bot-autofarm
Major2000/Albion-2024
Major2000/EFT-ESP-hack
MikeWoWOne/Fortnite-hack-version
MikeWoWOne/GameMaker-Studio-2-Crack
MikeWoWOne/HWID-spoofer-for-games
MikeWoWOne/IObit-Uninstaller-Latest-Version-Crack
MikeWoWOne/JetBrains-IntelliJ-IDEA-Crack
MikeWoWOne/KMS-Auto-Windows-and-Office-Activator
MikeWoWOne/Kiddions-mod-menu-gta-5
MikeWoWOne/KuCoin-trading-bot
MikeWoWOne/Lethal-Company-Hack
MikeWoWOne/LoL-hack-script
MikeWoWOne/Lumion-Crack
MikeWoWOne/Magix-Music-Maker-Crack
MikeWoWOne/Matlab-Crack
MikeWoWOne/Movavi-Video-Editor-Pro-Crack-Download
MikeWoWOne/NARAKA-BLADEPOINT-Hack-Free
MikeWoWOne/NEAR-HOT-WALLET-AUTOBOT
MikeWoWOne/Navisworks-Crack
MikeWoWOne/Nero-Burning-ROM-Crack
MikeWoWOne/NordVPN-Pro-Crack-Full-Version
MikeWoWOne/hamster-kombat-bot-free
MikeWoWOne/memefi-coin-crypto-bot
Molano11/Nero-Burning-ROM-Crack
Molano11/Youtube-365-Auto-upload-cheat-checker
Ozkaynak-Sucuk/1inch-bot
Ozkaynak-Sucuk/ARK-radar-hack
Ozkaynak-Sucuk/Albion-2024
Ozkaynak-Sucuk/Apex-2024
Ozkaynak-Sucuk/Autodesk-Maya-Crack
Ozkaynak-Sucuk/BitMEX-trading-bot
Ozkaynak-Sucuk/Bitfinex-bot
Ozkaynak-Sucuk/Blum-auto-bot
Ozkaynak-Sucuk/Coinbase-pro-trading-bot
Ozkaynak-Sucuk/Cs-2-Hack-Skinchanger
Ozkaynak-Sucuk/Discord-Nitro-Alt-Generator-Free
Ozkaynak-Sucuk/Driver-Booster-Pro-License-Key-Crack
Ozkaynak-Sucuk/Fc-24-Hack-Free
Ozkaynak-Sucuk/FiveM-Hacks-2024
Ozkaynak-Sucuk/Fixing-Error-kernelbase
Ozkaynak-Sucuk/Fortnite-hack-version
SpacyXyt/Cinema-4D-Crack
SpacyXyt/LoL-hack-script
V-arc/Silverfish
batuhanodbs/FiveM-Hacks-2024
blackvn05/ReiBoot-Pro-Crack-Download-Free
dblancolascarez/CCleaner-Crack
jgprimaki/Microsoft-Office-2024-Cracked-Version
jzhou8881/Discord-Nitro-Alt-Generator-Free
jzhou8881/Driver-Booster-Pro-License-Key-Crack
jzhou8881/EFT-ESP-hack
jzhou8881/ESET-NOD32-Antivirus-Crack
jzhou8881/Earnings-on-CS2-trades-CS-Trading-helper-Buff163
jzhou8881/Fc-24-Hack-Free
jzhou8881/Filmora-License-Key-Crack-Download
jzhou8881/FiveM-Hacks-2024
jzhou8881/Fivem-Hack-undetected
jzhou8881/Fixing-Error-0x80004005-Unspecified
jzhou8881/Fixing-Error-0x80070002
jzhou8881/Fixing-Error-0x80070005-Access-Denied
jzhou8881/Fixing-Error-0x8007000E
jzhou8881/Fixing-Error-0x80070057-Invalid-Parameter
jzhou8881/Fixing-Error-0x80070424-Specified-Service
jzhou8881/Fixing-Error-0x80070570
jzhou8881/Fixing-Error-0x80072EE7
jzhou8881/Fixing-Error-0x8015DC12
jzhou8881/Fixing-Error-0x803F8001
jzhou8881/Fixing-Error-0x887A0005-DirectX
jzhou8881/Fixing-Error-0x887A0020
jzhou8881/Fixing-Error-0xC000007B
jzhou8881/Fixing-Error-0xC0000142
jzhou8881/Fixing-Error-0xc0000005
jzhou8881/Fixing-Error-0xc00000ba
jzhou8881/Fixing-Error-BEX
jzhou8881/Fixing-Error-d3dx9-43-dll
jzhou8881/Fixing-Error-kernelbase
jzhou8881/Fortnite-hack-version
jzhou8881/Free-Crypto-Trading-Bot-Download
lixvr/1inch-bot
lixvr/BitMEX-trading-bot
lixvr/KuCoin-trading-bot
lixvr/Sandbox-CryptoBot
lixvr/eTukTuk-CryptoBot
teenjay/Sound-Forge-crack
teenjay/Steam-account-autoregger-creation-of-maFile
teenjay/Sublime-Text-crack
teenjay/TFT-Unlocker-Tool-FUll
teenjay/TeamViewer-Latest-Crack-2024
teenjay/The-unifier-is-both-Video
teenjay/Toon-Boom-Harmony-Crack
teenjay/Top-Osu-Hacks-2024-Aim-Assist-Bots-and-More
teenjay/TradingView-scripts
teenjay/Uniswap-bot
teenjay/Unity-Pro-Cracks
teenjay/VLC-Media-Player-Crack
teenjay/Vape-V4-Crack-Kangaroo
teenjay/Youtube-365-Auto-upload-cheat-checker
teenjay/ZBrush-Crack
teenjay/xBLAST-auto-bot
teenjay/yescoin-bot-installation
yCodezao/Microsoft-Office-2024-Cracked-Version
yCodezao/Microsoft-Project-Crack
yCodezao/NZT-Poker-AI-Bot-17-Rooms-Cash-Fish-Monitor
yCodezao/Notcoin-crypto-bot
yCodezao/Parallels-Desktop-Crack
yCodezao/Path-Of-Exile-Hack
yCodezao/Pinnacle-Studio-Crack
yCodezao/PlayDoge-Auto-Farm-and-Bot-Setup
yCodezao/Pro-Tools-Crack
yCodezao/ProtonVPN-Free-Crack-2024
yCodezao/ReiBoot-Pro-Crack-Download-Free
yCodezao/Revit-Crack
yCodezao/Rhinoceros-Crack
yCodezao/RisePro-Stealer-HVNC-Crack
yCodezao/SEED-SEARCHER-Crypto-Checker-30-Wallets
yCodezao/Sandbox-CryptoBot
yCodezao/ShibaShootout-CryptoBot
yCodezao/Snapster-autobot
yCodezao/SolidWorks-crack
yCodezao/cs2-hvh
yCodezao/pixel-wallet-bot-free
ySunSh1ne/JetBrains-IntelliJ-IDEA-Crack
yessine-agrebi/AOMEI-Partition-Assistant-Cracked-Software
01289jj/Blum-Auto-Clicker-Download-2024
037signedxyz/Roblox-Blox-Fruits-Script
0kenftr/h4ck-f0rtnite
123456789433/SonyVegas-2024
140683/Valorant-H4ck
157vr/Overwatch-2-Esp
19Papaj08/1express-Vpn-Free-2024
1imanishimwe/-Spotify-Premium-Crack-For-PC-2024-LifeTime-Licence
20Mahmoud/Roblox-Solara-Executor
28larsosamj/KRNL-Executor
2TheQueen2/Adobe-Express-2024
2kv1b4/Roexec-Executor
2xAQUA/modmenu-gta5-free
3040250900/Adobe-Express-2024
32r1/Nexus-Roblox
3hshshpq/Adobe-Express-2024
441414141414whitelisterpic0012304140402/Roblox-Trigon
68aro/1-Valohackk
7urs/cheat-apex-legends-download
8SoloLeveling/LOL-Skin-Changer-2024
9zrtw3e/cheat-apex-legends-download
A22G-eng/Adobe-Acrobat-Pro-2024
ABF2024/Adobe-Acrobat-Pro-2024
AIBestSoftwareGames/APE-Wreck-League
AIBestSoftwareGames/Big-Time-BIGTIME
AIBestSoftwareGames/Borderless-Gaming
AIBestSoftwareGames/Clash-of-Lilliput-COL
AIBestSoftwareGames/Delysium
AIBestSoftwareGames/GameBuild
AIBestSoftwareGames/GamerCoin-ghx
AIBestSoftwareGames/Gods-Unchained
AIBestSoftwareGames/Hamster-Kombat
AIBestSoftwareGames/HiFi-Gaming-Society
AIBestSoftwareGames/Karrat
AIBestSoftwareGames/Land-Of-Conquest-SLG
AIBestSoftwareGames/MAGIC-Treasure
AIBestSoftwareGames/MOBOX
AIBestSoftwareGames/MYTH-Enter-the-Mythos
AIBestSoftwareGames/Matr1x-Fire
AIBestSoftwareGames/My-Neighbor-Alice
AIBestSoftwareGames/Nakamoto-Games-naka
AIBestSoftwareGames/Oasys-OAS
AIBestSoftwareGames/PRIME-Parallel
AIBestSoftwareGames/PROM
AIBestSoftwareGames/Pixels
AIBestSoftwareGames/Radio-Caca-raca
AIBestSoftwareGames/SweatCoin
AIBestSoftwareGames/The-Sandbox
AIBestSoftwareGames/UPDATED-GamingPCSetup
AIBestSoftwareGames/UPDATED-Steam-Economy-Enhancer
AIBestSoftwareGames/UPDATED-SteamAchievementManager
AIBestSoftwareGames/UPDATED-SteamBot
AIBestSoftwareGames/Undeads-Games-UDS
AIBestSoftwareGames/Vulcan-Forged-pyr
AIBestSoftwareGames/WAXP-Spinnia-World
AIBestSoftwareGames/Wilder-World-wild
AIBestSoftwareGames/axs-Axie-Infinity
AIBestSoftwareGames/dar-Mines-of-Dalarnia
AIBestSoftwareGames/enj-Enjin-Coin
AIBestSoftwareGames/gala-Gala-Games
AIBestSoftwareGames/gmt-STEPN
AIBestSoftwareGames/ilv-Illuvium
AIBestSoftwareGames/mana-Decentraland
AKASHROUR/Roblox-Bunni
ALINIHAD2024/cheat-escape-from-tarkov
ANTUF/AquaDiscord
ASTRO226/sims-4-cheat
ASTRO226/sims-cheat
ASUSdavy0/Solara-Executor-Roblox
AXLJEREBY/Capture-One-23-Pro-for-MacOS-and-Windows
AYao-9R/Nexus-Roblox
Aaron-656/Bee-Harvest-autoclicker
AbdallaFathy1121/Adobe-Creative-Cloud-2024
AbdallaFathy1121/Adobe-Premiere-Pro-2024
AbdulGani207/Al-Photoshop-2024
AbdullahWajid1999/m0dmenu-gta5-free
AbdulrahmanFa2hy/FL-Studio
Abhinavpatra/apex-legends-cheat-download
Aboodwaddah/r0blox-synapse-x-free
Abovfrfr/apex-legends-cheat-download
Adam163812/CrystalTool
AdeiltonPereiraAlves/BlazingTool
AdeiltonPereiraAlves/ShadowTool
Adencaid/Roblox-Nexus
AdesimaWahab1/Canva-Pro-2024
Adeson2000/Photoshop-AI-Free-2024
Ahktar/r0blox-synapse-x-free
Ahmedraza1405/Dead-by-Daylight-Hacks-No-Ban
Ahmedraza1405/Fixing-Error-0x8007000E
Ahmedraza1405/Free-Library
Ahmeedkhaled/BrtWallet
AidenTecheRoberts/DEX-JavaScript-Triangular-Arbitrage-Bot-V5-AidenTecheRoberts
Aizen1220/FL-Studio
Aj-Butt/counter-str1ke-2-h4ck
AjinGixtas/Adobe-Premiere-Pro-for-MacOS-and-Windows
AjmalAfghanistan/Twitch-View-Bot
AjmalAfghanistan/YouTube-View-Bot
Ajtech147/Roblox-Krampus
Al-hussein31/Movavi-Video-Editor-Plus-for-MacOS-and-Windows
Alaaelwakel/CrystalTool
Alessandrofhs/AquaDiscord
Alex007iv/SketchUp-Pro-free-2024
Alex23603/Adobe-Media-Encoder-for-MacOS-and-Windows
Alexadre-Guerrero/cheat-apex-legends-download
Alexdmz1/Dayz-Cheat-H4ck-A1mb0t
Alguien061508/Discord-AllinOne-Tool
AliouDiop/ESET-KeyGen-2024
Allan18ajanel/Canva-Pro-2024
AlohaRaycin808/Minecraft-Vape
AlvaroPerezDominguez/Final-Cut-Pro-for-Mac-OS
Aman7093/iMyFone-AnyRecover-Activated-Version
Amateurcoder242/R6-MaxPanel
Amit41446/Roblox-Blox-Fruits-Script-2024
Amobiope92/Discord-AllinOne-Tool
AnaCCMessias/IDM-Activation-Script-2024
Andreizl/Discord-AllinOne-Tool
Androwie/m0dmenu-gta5-free
Anviktor/Solara-Executor
AprilCalanglang/f0rtnite-h4ck
Apurba94/Roblox-Blox-Fruits-Script-2024
ArasyD/BrtWallet
AravindanRamesh/Roblox-Blox-Fruits-Script
ArdyGonzales/IObit-Driver-Booster-Pro-2024-free-Serial-Key
Arggus/Solara-Executor
ArielSergiomuhate19/BlazingTool
ArifMunawar/IDA-Pro-Keygen-2024
ArlisMaricle/Lunar-Executor
ArmandoA10/hwid-spoofer
Armanhossen12/Canva-Pro-2024
ArmarJun/IObit-Driver-Booster-Pro-2024-free-Serial-Key
Armin2328/OpenSea-Bidding-Bot-2024
ArsenioMendes/DaVinci-Resolve-Studio-MacOS-and-Windows
Artur-mDeters/CosmicStar
Asep-SR/Wondershare-Filmora-for-MacOS-and-Windows
AshleyNatalia/Xbox-Game-Pass-Activator-Free-2024
Ashref0/Rainbow-S1x-Siege-Cheat
Astiin/PhotoDiva-Pro-free-2024
Astral2721/roblox-scripts-solara
AstroX10/whatsapp-bot
AtharvaKodre/PhotoDiva-Pro-free-2024
AvacadoWizard120/roblox-scripts-solara
Axsle-gif/h4ck-f0rtnite
AyoubTposin/Discord-AllinOneTool-2024
AyoubTposin/NitroDream-2024
Azeem-800/Discord-AllinOne-Tool
Azuresian/Nexus-Roblox
BLsiriwardana/FL-STUDIO-24
BLsiriwardana/Wondershare-Filmora-14-Free
BOUSSENGUI-MBOUALA-Jacques-Danis/SketchUp-Pro-free-2024
Barkard/ShadowTool
Bartekkk21/cheat-apex-legends-download
Bassmalahadoui/SilenceGen
Bawdaj528/Xeno-Executor
BegginnerCoder21/Autodesk-AutoCAD-2024-for-MacOS-and-Windows
BeilZeraN/Al-Photoshop-2024
Bekaensarmu/BioGuard-Hwid-Spoofer
Beluga633/minecraft-cheat2024
Benfoenix/roblox-scripts-solara
Betterlov/OpenSea-Bidding-Bot-2024
Bigjames105/PhotoDiva-Pro-free-2024
Blalangf86/FL-Studio
Bleron1i/SeedTool
Botellon/cheat-apex-legends-download
BouNty9659/m0dmenu-gta5-free
BrayanAugusto/SoLBF
BruhuwuXD/Roblox-Blox-Fruits-Script-2024
BrunoSenigalha/Sony-Vegas-Pro-2024
Bryony-B/Nexus-Roblox
BrysonAppalsamy/Warz0n3Ch3a7
Bushed51/roblox-scr1pts-s0lara
CacadorDeArthur/Solara-Executor-Roblox
CadeRastyyy/Roblox-Carbon
Cang250904/r0blox-synapse-x-free
Carlthenpcprogams/Roblox-Hydrogen
Casko00/wallet-stealer
CatherineRamy/roblox-scripts-solara
Charlotte871/Hydrogen-Executor-v2.642
Chavomu/FrogMates-autoclicker
Chidera-M/AquaDiscord
ChristianHyp/Oasis-Bot
Ckyle30/BlazingTool
ClearDamage/SketchUp-Pro-free-2024
CodeWithAmrita/Autodesk-Inventor-2024
CodeWithAmrita/ESET-KEYGEN
ConcepcionPaul/BG3_Camera_Hack
ConcepcionPaul/Defi-Bot
ConcepcionPaul/Fixing-Error-0xC000007B
CosmoGT-dev/cheat-apex-legends-download
Cris20034/Defi-Bot
Cris20034/Fixing-Error-0x803F8001
Cris20034/Fixing-Error-0xC000007B
Cris20034/Fixing-Error-0xc0000005
Cris20034/Fixing-Error-BEX
Criswesdy/counter-str1ke-2-h4ck
CrockYT/hack-blox-fruits-free
CrystalDustt/Canva-Pro-2024
Cskhero221/CosmicStar
DOGECODER69/Apex-Legends-Maphack
DOJDOXER/callofdutywarzone-hack
DYxN-1001/SeedGn
Daito-Raigar/IDA-Pro-Keygen-2024
Daniel-gon/EthMiner-2024
Daniel-gon/Solana-Token-Creator
Daniel-gon/Solana-Trading-Bot
Danielmakha/ETH-MEV-BOT
Dantesx43/SonyVegas-2024
DatBoiComfy/Pixel-Gun-3D
Davidogola/Discord-AllinOne-Tool
DebbyKogs/cheat-escape-from-tarkov
Dejou-H/ESET-KeyGen-2024
DeleteArm/Roblox-Blox-Fruits-Script-2024
Denis042/cheat-escape-from-tarkov
DevPedroL/Adobe-Express-2024
Dhaliwal053/IDA-Pro-Keygen-2024
DhrithiAshok/Flash-USDT-Sender
DiegDis/SonyVegas-2024
Dimplythree2/apex-legends-cheat-download
Dineshkumarmsc/GTA-5-Mod-Menu-2024
Dio1007/Nexus-Roblox
DogaoCC/minecraft-cheat2024
DooongJae/Xbox-Game-Pass-Activator-Free-2024
DouaaAl/Xbox-Game-Pass-Activator-Free-2024
Dovik-GIT/Gradient-Network-Bot
DrakonHellsworth/Wemod-Premium-Unlocker-2024
DuuArdo/Telegram-Scraper
DuyBui1811/Lunar-Executor
Dzakwanandra/cheat-apex-1egends-d0wn1oad
ELBERTOUCH/SilenceGen
EduardaSantosdS/Canva-Pro-2024
EduardaSantosdS/Sony-Vegas-Pro-2024
Eduardo8006/CrystalTool
Eduardo8006/SeedTool
EffiEmmanuel/ShadowTool
ElcioSouza/roblox-syn4pse-x
Elson10githubio/SilenceGen
Enano1213/Wemod-Premium-Unlocker-2024
Endelkys/free-NFT-art-generator
Envin69/Roblox-Blox-Fruits-Script-2024
EvilKaiser1/Sony-Vegas-Pro-2024
Excalibre50/counter-str1ke-2-h4ck
EzatAllah/Spotify-Premium-for-free-2024
Ezequias98/Sony-Vegas-Pro-2024
FETHUMOHAMMED/Xbox-Game-Pass-Activator-Free-2024
FLAME4229/Roblox-Horizon
Fadliium/Stardew-Valley-Cheat
Falledkid/m0dmenu-gta5-free
Feeju/Adobe-After-Effects
Feeju/Photoshop-2024-No-Crack
FernandoKambambi/Spotify-Premium-for-Free-2024
Filosofosaurio/Delta-Executor
Flameblazehero/Acrobat-Download-Free
Flameblazehero/Adobe-Illustrator-Herunterladen-Free
Flameblazehero/DR-FONE-SETUP-2024
Flameblazehero/Wondershare-Filmora-Download-Free
Flaminz1/VatexRaider
FlashTheGamer199/BlazingTool
Fleets2/PhotoshopUpdate
FlqmzeCraft/cheat-escape-from-tarkov
Flxtra21/Roblox-Incognito
Foxhs12/Adobe-Express-2024
FoxyCodes234/roblox-scripts-solara
Franshuavo/HWID-Spoofer-Cleaner-2024
Franshuavo/IDM-ACTIVATOR-2024
FrogMan882/SonyVegas-2024
Fuzzy1289/ESET-KeyGen-2024
GENERADOR7799/Wave-Executor
GTA241/m0dmenu-gta5-free
Gabriel-Dias-Oliveira/Sony-Vegas-Pro-2024
Gabriel-Dias-Oliveira/Wemod-Premium-Unlocker-2024
Gabriel345/Nexus-Roblox
GabrielDamiani/Shadow-ClipperMalvare
GabrielDamiani/ShadowUnlocker
GabrielScipioni/Adobe-Acrobat-Pro-DC-23.003.20244-Intel-Apple
Gabrielmaste/Treasure-Tapper-autoclicker
GauravSakariya99/GTA-5-Mod-Menu-2024
GauravSakariya99/Xbox-Game-Pass-Activator-Free-2024
Gde0/Sony-Vegas-2024
Genkai91/bnb-hunter
Genkai91/trx-wallet-finder
GerardoR17/m0dmenu-gta5-free
Gil100-M/DCRAT-2024
Gil100-M/Fixing-Error-0x887A0020
Gil100-M/LoL-hack-script
Githud320/MultiLauncher
Gnifh01/SketchUp-Pro-free-2024
GoDToD/Exitlag-Free-2024
GoDToD/OpenSea-Bidding-Bot-2024
GreatLightIntheDarkness/minecraft-cheat2024
Grizzl21/Adobe-Creat1ve-Cl0ud-Full
GwenStasee/SilenceGen
Gwillop/roblox-executor
GxDongV/minecraft-cheat2024
HOANGVANSON9999/Canva-Pro-2024
HThach2k3/Solara-Executor
Haider-khalid/Topaz-Gigapixel-AI-tool
HakkeMitch/Rust-App
Hecker04/BrtWallet
HenryCL/ShadowUnlocker
HenryCL/SilenceGen
Herdavid03/Adobe-Animate
Herdavid03/Adobe-Express
Hesamiiii/Adobe-After-Effects-macOS-
HiCaptain202/Dogs-Coin
Hippomed-entreprise/Solara-executor
Hira20/AquaDiscord
Hira20/Spotify-Premium-for-free-2024
HoaxKY/Roblox-Blox-Fruits-Script-2024
HolaPepsicola/Dead-by-Daylight-Hacks-No-Ban
HolaPepsicola/Fixing-Error-0x80070570
HolaPepsicola/Fixing-Error-d3dx9-43-dll
Holdmyhacks/Dogiators-autoclicker
HossamAbdElfadil/counter-str1ke-2-h4ck
HuskyDK/cheat-escape-from-tarkov
ITASHIs/JJsploit
ITcattt/ESET-KeyGen-2024
ITcattt/HWID-Spoofer-and-Cleaner-2024
IVExShowcase/cheat-apex-legends-download
Ianaaa354/Roblox-Vega
IcYFlapz/Evon-Executor
Idrissip07/Fake-Crypto-Sender
Idrissip07/UnlockTool-Activated-Version
IgorDmoura/f0rtn1t3-h4ck-fr33
IgorJF/Dayz-Cheat-H4ck-A1mb0t
ImranGmr/cheat-escape-from-tarkov
Ineedexcutor/Hamster-Kombat
JJchinchillalanziano/Wave-executor
JPKS15/Dogs-Telegram
JRArobot/cheat-apex-legends-download
JUMOX18/Roblox-Blox-Fruits-Script-2024
Jaber-codes-Mo/Sony-Vegas-Pro-2024
Jaber-codes-Mo/Wemod-Premium-Unlocker-2024
Jackvv123/SonyVegas-2024
Jamjam1234927/ETH-MEV-BOT
Jellycr2/m0dmenu-gta5-free
Jenny-mod3256/r0blox-synapse-x-free
JeremiahIlunga/IObit-Driver-Booster-Pro-2024-free-Serial-Key
Joao-Roberto7/-PornHub-Premium
JoashQuinn/AIMDream-2024
Julian-dev2/Dead-by-Daylight-Hacks-No-Ban
Julian-dev2/Fixing-Error-0x80070002
JunaidYousafzai/Exitlag-Free-2024
JunaidYousafzai/PhotoDiva-Pro-free-2024
KADU176/Roblox-Nihon
KDrop25/Blum-Auto-Clicker
KKKkK33340/minecraft-cheat2024
KRUU500/Stake-predictor
KaiCheBeiZhua/Rainbow-S1x-Siege-Cheat
Kakabaka12323/Roblox-Blox-Fruits-Script-2024
KanaChee/Fixing-Error-0x80070005-Access-Denied
KanaChee/Fixing-Error-BEX
KanaChee/Fixing-Error-d3dx9-43-dll
Kareem-Ibrahim-Mahmoud/Plugin-Pack-Tool
Kareemmulhum/SeedGn
Karlaglezh/SeedTool
Kellen122/IObit-Driver-Booster-Pro-2024-free-Serial-Key
Kelly-McGowan/prhb-loader
KelvineSilva/ShadowTool
KingSayy3d/r0blox-synapse-x-free
Kintzleykiller/minecraft-cheat2024
KipruttoMutai/Autodesk-Inventor-free-2024
KipruttoMutai/SketchUp-Pro-free-2024
KisoStar/Evon-Executor
Knox1029/Sony-Vegas-Pro-2024
Kokopetrov/Zorara-Executor
Krzychowskyy/PhotoDiva-Pro-free-2024
Kubix14/SonyVegas-2024
Kukupie123/Adobe-Acrobat-Pro-2024
Kukupie123/Adobe-After-Effects-2024
Kuronin26/Nexus-Roblox
LEOANTONY2002/Spotify-Premium-for-free-2024
LOOTSTAN/Roblox-Horizon
LOSTIE09/r0blox-synapse-x-free
LOWAISDQFIJQSJDFUOI/Wondershare-DrFone-Activated-Version
Laithgaming5power/callofdutywarzone-hack
LandonPasana21/Roblox-Blox-Fruits-Script-2024
LavenderMonody/cheat-apex-legends-download
LeeeSe/HeadCoin-autoclicker
LeonardERacagni/r0blox-synapse-x-free
LilSlippyVert/minecraft-cheat2024
Lolboblol/minecraft-cheat2024
Lordsatanthenuker/DiscordUniverse
Lua-Scripted/Blox-Fruits
Lua-Scripted/Da-Hood
Lua-Scripted/Fisch
Lua-Scripted/PETS-GO
Lua-Scripted/The-Strongest-Battlegrounds
Lua-Scripted/Toilet-Tower-Defense
LuigiGamesScripts/Roblox-Blox-Fruits-Script-2024
LuisMariaGomez/Sony-Vegas-2024
Luka053/roblox-scripts-solara
Lukasdrexler22/VOICEMOD-PRO
LuksMB/IDA-Pro-Keygen-2024
LuksMB/IDM-Activation-Script-2024
Lutesy44/Roblox-Electron
M0shaa/SonyVegas-2024
MCKingdoms/Pubg-Cheat-Menu
MINECRAFTPVP889/minecraft-cheat2024
MOXBYtv/UnlockTool-Activated-Version
MTCFDFH/cheat-apex-legends-download
Maarufa/Fixing-Error-0xC0000142
Maburo951/Adobe-After-Effects-Tool
Mackveli8/Brute-Wallet
Macless56/Rainbow-S1x-Siege-Cheat
Manuelrspam/SilenceGen
Marcos-Dantas/IDA-Pro-Keygen-2024
Marcos-Dantas/ProtonVPN-Free-2024
Masaruz101/Octoplus-FRP-Tool-Activated-Version
Mateo2416/Roblox-Scriptify
MaxiePad2/roblox-scr1pts-s0lara
Maxricky55/Final-Cut-Pro-for-Apple-macOS
MichaelGydin/Fixing-Error-0x80070057-Invalid-Parameter
MichaelGydin/Fixing-Error-0x80070424-Specified-Service
Mike123r/NFT-Art-Generator
MikeBojangles/token-sniper-bot
Mini-Bobo/callofdutywarzone-hack
Mink951/Roblox-Trigon
Mrmubeenff/Nezur-Executor
Mrvaugan88/cheat-apex-legends-download
MusashiSamaa/r0blox-synapse-x-free
Mvillegasbolivia/Chat-GptApi
Mvillegasbolivia/DCRAT-2024
Mvillegasbolivia/Fixing-Error-0x80004005-Unspecified
Mvillegasbolivia/Fixing-Error-0x80070005-Access-Denied
Mvillegasbolivia/Fixing-Error-0xc00000ba
Mvillegasbolivia/Hotmail-checker-brute-inbox
NEILASc/SonyVegas-2024
NXFi17/minecraft-cheat2024
NabHeyka22/r0blox-synapse-x-free
Nappxy/Evon-Executor
NearZeK/ether-finder
Nearl0601/Titan-Network-Bot
NguyenMG/Roblox-Synapse
Nhrepon/Sketch-Crack
Nikewaybuck/Nebula-Executor
NlsnHerlan/SonyVegas-2024
NoelTejeda/Adobe-Acrobat-Pro-2024
NoelTejeda/Adobe-After-Effects-Free-Activator
NoodAFK/FreeFirePC_panel_src
NotSyro/Midnight
Nothing12321/Proxy-Grabber
Nothingg2011/r0blox-synapse-x-free
NungisRungis/Solara-Executor
Obito770/Tronix-auto-bot-
OfficialErmDev/Roblox-Blox-Fruits-Script-2024
OpacGOD12/cheat-apex-legends-download
OsmanCiberOsman/KRNL-executor
PETERLOLPETERKAT/Roblox-Blox-Fruits-Script-2024
Papuka12/Sentiment-FreeTool
Patschannel/Lunar-Executor
Philou2/Adobe-Premiere-Activated-Free-Download
Philou2/Photoshop-Activated-Free
PimmadaJ/Fixing-Error-0x80004005-Unspecified
PimmadaJ/Fixing-Error-0x80070002
PimmadaJ/Fixing-Error-0x8007000E
Poison987/Astolfo
Przemx9/cheat-apex-legends-download
RBBOOY/counter-str1ke-2-h4ck
RM-CIEL/BlazingTool
RM-CIEL/ShadowTool
RakoBman/cheat-apex-legends-download
Rapaulpuss/Solara-Executor
Rapaulpuss/Solara-Executor-Roblox
Ray12050/cheat-apex-1egends-d0wn1oad
Ray700/Adobe-Photoshop-Crack
Ray700/Filmora-Crack-Free
Rbx-dev-scripts/DOORS
Rbx-dev-scripts/Tower-Defense-Simulator
RedDoesStuff/cheats-genshin-impact
RedRisem/Spotify-Premium-for-free-2024
Redwingshunt/Adobe-After-Effects-2024-
Redwingshunt/Fl-Studio-2024
RishBroUltraProMax/Nevermiss
Rogerioerio/script-hub-blox-fruit
Romeo12243563/Arceus-Executor
RoseCrib2833078/Roblox-AppleWare
Rubix558/Dayz-Cheat-H4ck-A1mb0t
RunnerFinder/DEX-JavaScript-Front-Running-Bot-V4-RunnerFinder
SAMAIOEC/download-minecraft-skin
SAMAIOEC/free-vpn-for-pc
SARAHITGIP/Roblox-Scripts-Solara
SHAD0WBULLET707/-Seed-Phrase-Holder
SKEY-308/Lobit-Malware-Fighter-Tool
SNjserge/JJsploit
SRohit1910/Seed-Phrase-Checker
SUPAAAMAN/m0dmenu-gta5-free
SadLifeCoder/DEX-Triangular-Arbitrage-Bot-V4-SadLifeCoder
SaierForceTwo/-VPN-Crack
SaineDoctrine/Quai-Bot
Saju-Sajjad/Adobe-Acrobat-Pro-2024
Saju-Sajjad/Fl-Studio-2024
Salton30/roblox-executor
Salty1313/cheat-apex-legends-download
Samejon/Chat-GptApi
Samejon/Fixing-Error-0x80070424-Specified-Service
Samejon/Hotmail-checker-brute-inbox
SanctusTR/m0dmenu-gta5-free
Sayan666/Sketchup-pro-macOS
ScaryUsername/m0dmenu-gta5-free
Scriptztyz/Nexus-Roblox
ServGuard/Raccoon-autoclicker
Settu1998/Bitcoin-Miner
Shukunkami/FL-Studio
Shura23/Hiddify
SiJuBo/minecraft-cheat2024
Sidodido/spotify-Premium
SilentClaw27/Solara-Executor
SinisterSane/Telegram-member-adder
Sirajjaris/Roblox-Oxygen
Skinnycoder247/roblox-scripts-solara
Sleyzen/Ink-Bot
Slipstream-Syndicate/SeratoDJ-Pro-Tool
Soarescvrl/Allora-Farmer
SolanaSoft/Free-Fire-Panel
SolaraExev4/Solara-Executor
SonofDev/FFH4X
SonofDev/free-fire-pc-panel
Souza-kk/r0blox-synapse-x-free
Spammer69420/m0dmenu-gta5-free
Spinilian/Celex-Executor
Starkidd631/Solara-Executor
Stkill292/Earnings-on-CS2-trades-CS-Trading-helper-Buff163
Stkill292/Fixing-Error-0x8015DC12
Stkill292/Sentiment-FreeTool
Sunken-Wood/minecraft-cheat2024
Super-Gufa888/Rocky-Rabbit-autoclicker
Synthriot/Piggy-Bank-autoclicker
TIMREX-TM/Nexus-R0blox
TTI-nelson/r0blox-synapse-x-free
TVEGesdOfficial/minecraft-cheat2024
TapetalArray/ndk-arm64-linux
Tarakumari/Celex-Executor
TeefsMy/Wondershare_FilmoraFull
TeensFa/1v-Adobe-Illustrator
TeensFa/Full-Adobe-Premiere
TempleCIS3515/DeadLock
Tenelbacon/spoofer
Thayven/Spotify-Premium-for-free-2024
TheBirdsman04/Parallels-Desktop-for-Mac
TheCoolLegendary/Adobe-Photoshop
TheGamingISLE/roblox-scripts-solara
TheSoundCode/DEX-Triangular-Arbitrage-Bot-V4-TheSoundCode
Theus-Alves/Nexus-Roblox
TikiTikiPlus/ESET-KeyGen-2024
TikiTikiPlus/HWID-Spoofer-and-Cleaner-2024
TimothyFerbes/Hydrogen-Executor-v2.642
Titaniowingcl/-NFT-Art-Generator
TithdavidRa/roblox-scripts-solara
Titsou/AI-Crypto-Signals-Bot
Titsou/AI-Crypto-Trading-Bot
Treepy3/PhotoshopPack
Tron-Software11/solana-pumpfun-token-creator-comment-sniper-bundler-bot
Tuafo/callofdutywarzone-hack
TwistedGalaxy10/r0blox-synapse-x-free
Tygo090/Executor-Script-Roblox
UNITED-911/Moonbix-autoclicker
USER11009977/Nevermiss
UltraFat6410/Grass-Bot
Updated-Scripts/Adopt-Me
Updated-Scripts/Anime-Vanguards
Updated-Scripts/Bee-Swarm-Simulator
Updated-Scripts/Brookhaven-RP
Updated-Scripts/Dress-To-Impress
Updated-Scripts/Murder-Mystery-2
Updated-Scripts/Pet-Simulator-99
Urstrulytrey/roblox-scr1pts-s0lara
Vanity12345/roblox-scripts-solara
VeryPeeved/minecraft-cheat2024
VilosmZX/roblox-scripts-solara
VinRblx658Exploidsscripds/Roblox-Blox-Fruits-Script-2024
Vinn7545/Solara-Roblox-executor
Vinn7545/Wave-executor
VinosoPizzas/1express-Vpn-Free-2024
VinosoPizzas/SketchUp-Pro-free-2024
VurB/Roblox-Frostware
WGreizer8/ESET-KeyGen
WH1T3-E4GL3/Commandro
WQUIC/Ether-UI
WackyModerAlt/m0dmenu-gta5-free
WeLoveEmre/roblox-script-executors
Web3John/DEX-JavaScript-Triangular-Arbitrage-Bot-V5-Web3John
XDMOPAK/Roblox-Moon
Xaario/rob10x-synapse-x-free
Xangai-xp/Roblox-Blox-Fruits-Script-2024
Xennec/cheat-apex-legends-download
XiaoTouMingyo/PentesterTools
XxExoticx/SeedTool
YOOVOOYXD/stake-prediction
YaelGomm/Defi-Bot
YaelGomm/Fixing-Error-0x80070570
YaelGomm/Fixing-Error-0x887A0020
Yazeed08/Blum-Claimer
YuB-W/Domain-Executor
Yulistama/TFT-Unlocker-Tool
YusufHalilCATAL/FrogTrader-autoclicker
Yusufiqbal15/WEMOD
ZAQxlx293/Rainbow-S1x-Siege-Cheat
Zernitye/callofdutywarzone-hack
Zezao565/Valorant
ZhongZhang96/Movavi-Screen-Recorder
a9-shou/AquaDiscord
abdulahad-DI/apex-legends-cheat-download
abdydeymar/SketchUp-Pro-free-2024
abubakar0317/BlazingTool
adityasharmavlogger/CS2Dream-2024
afnei/Carnom-Wallet-Cracker
agostik/-Seed-Phrase-Holder
ahmed18sab/Adobe-Acrobat-Pro-2024
ahmedafeef/Roblox-Blox-Fruits-Script
aku0905/SketchUp-Pro-free-2024
al3jandr0xx/HWID-Spoofer-and-Cleaner-2024
al3jandr0xx/Spotify-Premium-for-free-2024
aldenpogznet22/Hamster-Bot
aleh1632/apex-legends-cheat-download
alejorodriguez/solara-executor-rblx
alex007prime/BlazingTool
alexa19990/Rusherhack
alexandraselina/BrtWallet
alexcuaran/CosmicStar
alexhoang9/Dead1ock-h4ck
alexistech14/KRNL-Executor
alexito13321/moonbix-claimer
alialmasslmane885/Discord-AllinOne-Tool
allagolovinova52/Wallet-Cracker-Finder
aloahsho77/ETH-Miner
alphadiib/PUBG-Cheat
altyndaky/Fixing-Error-0x8015DC12
amazing562/Revo-Uninstaller-Pro-No-Crack
amejia-finkok/Fake-BTC-Sender
amjdallfy/Exitlag-Free-2024
amorenouc/SolaraInjector_RBL
amr2777/Black-Myth-Wukong-Repack
anasahmedshaikh/CrystalTool
anbnn757/Roblox-Blox-Fruits-Script-2024
andeground100wt8m/1ac-ARKSurvivalEvolvedc
andeground6xbwe/1ao-CallofDutyWarzoneMW2MW3o
andjelaak6/IDA-Pro-Keygen-2024
andreracodex/Camtasia-for-MacOS-and-Windows
anesssssss/cheat-apex-legends-download
angel8989/Roblox-Nihon
anhhuy-em/counter-str1ke-2-h4ck
anison200yrs/1ad-CounterStrike2d
anonimskarlis/ESET-KeyGen-2024
antonybotello/Xbox-Game-Pass-Activator-Free-2024
arPotx/minecraft-cheat2024
ariciul100/Dayz-Cheat-H4ck-A1mb0t
ariefphoto/GTA-5-Mod-Menu-2024
aryabasu17/AquaticDiscord
aryabasu17/wallet-stealer
asdeenner53/Virtual-DJ-No-Crack
asdeenner53/WinRAR-Password-Cracker-Tool
asideglide373dnp/1af-DeadbyDaylightf
atexis7888/CrystalTool
atomicthefemboy/cheat-apex-legends-download
aulwarpX/MEV-UniswapBot
aussieguykvvq/1ah-Destiny2h
averagegamer2987/cheat-escape-from-tarkov
avingmrdarkman92/FL-Studio-No-Crack
awai-lc/m0dmenu-gta5-free
aymen36dw/SeedGn
bafymronterry8/JJsploit
bambi-gamer/Spotify-crack-v0.23--2025-
bambino85lw1f/1ad-ElderScrollsOnlined
baraa333/Valorant-H4ck
barsik200795ko/1an-GenshinImpactn
barxasymym10/GTA-5-Mod-Menu-2024
benbenbenbenbenAAAAAAAAHHH/Nexus-Roblox
berkjn/ESET-KeyGen-2024
bernardo-dev/Driver-Booster-Pro-2024
bernardo-dev/YoutubePlaylistDownloader-2024
best28156/cheat-apex-legends-download
bhalerao12/Dead1ock-h4ck
bimo15c/Roblox-Horizon
biowarriorpsix1984xumg/1as-Overwatch2s
blackdevil47ymym/AquaDiscord
blackmt01/SeedGn
bladewoodkickstartrtxo/1at-PathofExilet
blossombutt9586l0d/1ar-PUBGr
boludo1/callofdutywarzone-hack
bonfimm/Telegram-Blum
booboo-netoiparen/Criminality
boogabear-how/Canva-Premium-No-Crack
boogabear-how/Microsoft-PowerPoint-No-Crack
bossannymars1992/BedWars
bossmoldranz8glog/1am-RainbowSixSiegem
bosxz23/Minecraft-Rise-V6-Client
bratporuporz9wb/1al-RocketLeaguel
brenindexdev/SeedTool
brenoramon123/Xbox-Game-Pass-Activator-Free-2024
brijeshit47/SilenceGen
brunoafp/Meerkat-autoclicker
brunoplollato/Nexus-Roblox
bubarcost89/Pancake-Protectors-Crypto-Bot-Crypto-Game-Auto-Farm-Clicker-Cheat-Token-Hack-Api
bubbies68borne/petsgo
cIiqued/FL-Studio
cahb52/GRAPHISOFT-ArchiCAD-25-for-MacOS-and-Windows
cainshin/download-minecraft-skin
campbellshava/Spotify-Premium-for-free-2024
camposdev/Rainbow6-DemonPanel
cashpoppo/btc-trade-bot
cedriiccc/Wemod-Premium-Unlocker-2024
cell012/Xbox-Game-Pass-Activator-Free-2024
cesarm1987/DiscordUniverse
cesarm1987/Spotify-Premium-for-free-2024
chacha1629/notpixel
chatwhatthe/FL-Studio
cherrypiemosephad36mpj/1at-Rustt
chicken943/Creatures
chrismanatandi254/sony-reader
clammed/minecraft-cheat2024
cleanerjesus/Roblox-Blox-Fruits-Script
cloudsolart007/ZeusMenuApexLegends
cobetest/Dogs-Claim
codeder13/Call-of-duty-black-ops-6-Cod-bo-6-undetected-aimbot
cooldude994433/Warfare-Mod
coopa486/Wave-Roblox
crajis/BrtWallet
crazymenakiko723jw1/1at-TeamFortress2t
cricktage1096dy/1au-Valorantu
d4nndev/Pr3miere-Pro-2024
daban23/CrystalTool
daggertermenator9nva/1ad-Warframed
damonergth/minecraft-cheat2024
damz001/Fixing-Error-0x803F8001
dangnam12345vn/Roblox-Blox-Fruits-Script-2024
danys3269/Fake-Crypto-Sender
darkgxng/r0blox-synapse-x-free
darkhorse20096870/1ak-WorldofWarcraftk
darkmoondiscoatoh/bloxlua
datpro2062011/Roblox-Electron
deadmorose-dika/IObit-Driver-Booster-Pro-2024-free-Serial-Key
deadmorosenook3/IDA-Pro-Keygen-2024
deathlord130/Nexus-Roblox
deathlordgamer920/Discord-AllinOne-Tool
deb34367222222222/callofdutywarzone-hack
deeshbro/Dead1ock-h4ck
definitelynotrolly/GTA-5-Mod-Menu-2024
demonxaoca89bottle/DressTo
desaz86culme0zut/1ag-Adopt-Meg
dev-marsu/SoLBF
dev-marsu/WalletDucker
dev-marsu/walletST
developertusharkumar/IObit-Driver-Booster-Pro-2024-free-Serial-Key
devpedromachado/SketchUp-Pro-free-2024
devure/-Main-Telegram-AutoClicker
dh1349/Dayz-Cheat-H4ck-A1mb0t
dimarMJ03/Warzone-h4ck
dispathautoRetainReleaseReturnValue/Dayz-Cheat-H4ck-A1mb0t
dmsiman/OpenSea-Bidding-Bot-2024
doanthienminh1083/BlazingTool
doanthienminh1083/ShadowTool
domikmlckv/PhotoDiva-Pro-free-2024
doombringer2010yo7g/1an-Anime-Fighting-Simulatorn
dragonblood/Microsoft-Windows-and-Office-Activator-2024
dragonblood/Spotify-Premium-for-free-2024
driedmouseshield/SketchUp-Pro-free-2024
drop850/Bandicam-No-Crack
drsfd/SonyVegas-2024
duabaru2/Adobe-Acrobat-Pro-2024
duciaeli/Telegram-Hamster
ducky-godpets/IOBit-Uninstaller-Pro-No-Crack
dumbwhisper/FFH4X
duped12/Dogs-Telegram
dwertipynezameten/Roblox-Oxygen
dyarehakim0/Roblox-Nihon
elayaxoxo/PhotoDiva-Pro-free-2024
elias12vr/Nexus-Roblox
elthinshordekeep/Roblox-Incognito
elthinshordenysson/Heroes
emmanegodonou/SketchUp-Pro-free-2024
en143/Archicad-No-Crack
enverbashirov/EthMiner-2024
enverbashirov/OpenSea-Bidding-Bot-2024
envincebal/Adobe-Acrobat-Pro-2024
envincebal/IDM-Activation-Script-2024
epicdxoma/YesCoin-autoclicker
ericksonxd/hot-wallet-autoclicker
eron4u/TrumPump-autoclicker
erto7852/Nexus-Roblox
eslco/AutoEUServerless
ettoreribaudo/Solara-Executor
evankouassi/Fixing-Error-0xC0000142
evankouassi/Fixing-Error-0xc00000ba
evankouassi/gta5-DevMode
evankouassi/hwid-spoofer-all-games
evindoamanda25/SketchUp-Pro-free-2024
excut47red/Luna-Executor
eya1707/Solara-Executor-Roblox
faircitizen/Nexus-Roblox
fannykarasik4m5cm/1an-Brookhavenn
fannykotuk-1992/WpCracker
faringiceboxmwqt/1aw-Build-A-Boat-For-Treasurew
fatonoangel816/PDFelement-No-Crack
fchristian97/r0blox-synapse-x-free
fdgfdsggg/Roblox-Blox-Fruits-Script-2024
fekrisalem/Wemod-Premium-Unlocker-2024
fengxi223/Carnom-Wallet-Cracker-2024-macOS
ffhack123/Solara-Executor-Roblox
fireball643/Cubase-Pro-No-Crack
fireboy42gaxj/1au-Flee-the-Facilityu
fireboyandymirny/mm2script
fitrizeema/r0blox-synapse-x-free
fjc12/Nexus-Roblox
fladannymars-1992/Seliware-Executor
flamebearer-2100/SeedGn
floomeergaussboy/Anime
fmuiin14/BlazingTool
fmuiin14/ShadowTool
forbiddenkitkat/gtaonline-hack
fording26font/Roblox-Blox-Fruits-Script
fortic1/Vertus-autoclicker
fortniggtggu/Cryptic-Executor
foss-android/docker2tar
franciscofpv/Fixing-Error-0x80072EE7
freakmoot2716/counter-str1ke-2-h4ck
fsmdeveloper/hdo.box
fstina/Valorant-H4ck
funnyboimunke/UnlockTool-Activated-Version
galviv/flash-usdt-software
gamerproak/Roblox-Incognito
gamerq1025/Fake-Crypto-Sender
gamerquantuozw/1ai-Ableton-Livei
gaurav-vindeca/IObit-Driver-Booster-Pro-2024-free-Serial-Key
gazman613/SketchUp-Pro-free-2024
gdocq0/callofdutywarzone-hack
geegotti/FL-Studio
githubmainer14/Roblox-Executor
glitch-ui163/Wemod-Premium-Unlocker-2024
gm1008666/Pixie-autoclicker
gmiklazgazi/Xbox-Game-Pass-Activator-Free-2024
gogeta100/FL-Studio
goodcobra1984jwux/1ar-Piggyr
grasvale/Argon-Executor
gravelshaperflame4vfm/1ac-Royale-Highc
griderempark1992/Blade
gutsyheart696/Dandys
hack1232421/Roblox-Blox-Fruits-Script
hardskill81bwco/1aa-Shindo-Lifea
hardskillbenladenropm/1ay-Super-Hero-Tycoony
harley69691/h4ck-f0rtnite
hart46klatton/Roblox-Celery
heidaroyellow7/Spotify-crack-v0.23--2025-
heidaroyellow7/Uniconverter-No-Crack
hellbirdvimer76/Codex-Roblox
helloitsme12334/m0dmenu-gta5-free
helpbringer6ymym/Carbon-Executor
helpbringersx6x/1ax-Work-at-a-Pizza-Placex
henry1240/h4ck-f0rtnite
hiwaloye/CosmicStar
hoaan1995/Condi-Botnet-V9.2
hoangpm07/SeedGn
hotpantsbronze5/Evon-Executor
hotpantsbronze5/aascript
hxxps-aarush/callofdutywarzone-hack
hugodq/Wave-executor
iamcool1234q/minecraft-cheat2024
iamsaifale/Voicemod-Pro
ian-parra/CrystalTool
idml932021/zzz-cheat
idontrizz/roblox-scripts-solara
iib3xu/ESET-KeyGen-2024
ijaredmc/VALORANT-ESP-EXTERNAL-UNDETECTABLE
im-biyash/Al-Photoshop-2024
im-biyash/Shadow-ClipperMalvare
immortalfear1mgm5/1ay-Adobe-After-Effectsy
immortalfear3orhid/Anime-L
imnyxxx/Solara-Executor
imtiahanswe/Discord-AllinOne-Tool
intospace882/Autodesk-Autocad-No-Crack
irg0/AquaDiscord
itrkk/Xbox-Game-Pass-Activator-Free-2024
ivandkridd/trading-view-premium.
javicantos/IDA-Pro-Keygen-2024
jaydenth/Roblox-Synapse
jeantecni/Dead10ck-h4ck
jelefasongs/GTA-5-Mod-Menu-2024
jemmmyboi/Hamster-Clicker
jerrypooh5oxxs/1au-Adobe-Illustratoru
jiminxhz/SonyVegas-2024
jkapadiya/r0blox-synapse-x-free
jmacar/m0dmenu-gta5-free
joaolucasparada/S0LBF
joaolucasparada/Wallet-st
joaoteixeira7/PhotoDiva-Pro-free-2024
joefbmx1234/minecraft-cheat2024
johan123kl/OpenSea-Bidding-Bot-2024
johnnycleiton07/BrtWallet
johnnycleiton07/SeedGn
juanevelio/Fixing-Error-0x80070570
juanevelio/Fixing-Error-0xc0000005
juanevelio/Voice-Changer
kaio-cell/Tenorshare-Reiboot-Activated-Version
kakidrollie/cheat-apex-legends-download
kamel700/Delta-Executor
kaplya04/Sapphire-Plugin
karan-pawar1199/Adobe-Premiere-Free
katiamch/Wave-Executor
kenanisbedtime/Roblox-Celery
kenzie5364ki/Roblox-Vega
khanh181/PurpleStar
khanh181/SilenceGen
kheeclam/SketchUp-Pro-free-2024
kindblayde/BlazingTool
kingnotdeanpunk4/Canva-Premium-No-Crack
kirikdiscoatoh46/Haikyuu
kiz12/OpenSea-Bidding-Bot-2024
kloisova/Credit-Card-Generator
knightannymars0/Codex-Roblox
knightybird/HoldCoin-autoclicker
komyra33/Solara-Executor-Roblox
kotsbugger198203kb/1ac-Adobe-Acrobat-Proc
kotsdrdost691/VenomControl-Rat-Crack-Source
krasavik80/SeedTool
krekery888/1ab-Adobe-After-Effectsb
kristeryo/cheat-apex-legends-download
kristianrose/h4ck-f0rtnite
kurtzxitado/ESET-KeyGen-2024
l4r3in4/Lumion-Pro-Free
lKiper/cheats-genshin-impact-pc
ladyluck47gamer2cym/1ae-Adobe-Illustratore
lamphunk17lamphunk17/gradient-network-software
lan3flyingseiv/1ab-Affinity-Photob
lattex5/BlazingTool
lattexdwarf8pnmg/1ah-Atomh
leafilluminatorbofm/1ao-Adobe-InDesigno
ledwhite1996yxrv/1au-Adobe-Photoshopu
leivy82bkpm/1ak-Pet-Simulator-Xk
lemongekata1980fvom/1ah-Adobe-Premiere-Proh
lemonsegdapred/Autodesk-Autocad-No-Crack
lemonthemodder2/Dogs-Telegram
leonardoleoparo/Xbox-Game-Pass-Activator-Free-2024
leshiydestroffik94/Forsaken
lethanhtoan17/Roblox-Blox-Fruits-Script-2024
lindisrayescobar54/Jujutsu
lindisrayescobar54/Roblox-Scriptify
lnand0/r0blox-synapse-x-free
lovereyna003/Roblox-Moon
loxneszombak919hi8x/1az-Capture-One-Proz
lucifer9oaip/1an-Camtasia-Studion
lutherpc/Avast-Premium-Activated-Version
lyndertmanani/Filmora-13-Free
m-tobi/Nexus-Roblox
m3roof1441/roblox-scripts-solara
mOONtHEdEV2012/m0dmenu-gta5-free
mac2k23/Canva-Pro-2024
mac2k23/Fl-Studio-2024
maetatree585/Roblox-Synapse
mahounain7/Adobe-Premiere-Pro-macOS-
malwisp/SoLBF
malwisp/wallet-stealer
marcosgodoy/Wemod-Premium-Unlocker-2024
martinzsentori/Roblox-Blox-Fruits-Script-2024
mashiro-hue/Xbox-Game-Pass-Activator-Free-2024
masilos-prog/m0dmenu-gta5-free
masumion/Roblox-Executor
mateusborba/ScrooGgame-autoclicker
maxisco641/cheat-apex-legends-download
mazahakafunmaker32fwxy/1ah-Cinema-4Dh
mcnarybyloka33/AdoptMe
mdbyjidhasan1243/KRNL-Executor
megabottom33/DaHood
mell111dlfu/1ab-Corel-PHOTO-PAINTb
memogit18/BG3_Camera_Hack
memogit18/Fixing-Error-0x80070424-Specified-Service
memogit18/Fixing-Error-0x803F8001
memogit18/Sentiment-FreeTool
memogit18/gta5-DevMode
mendyolaughing/BrtWallet
miguelthenub/ExitLag
mihako86/Avast-Premium-Activated-Version
mikepostema/roblox-syn4pse-x
mikimaushunk719/ShadowTool
milind64/CosmicStar
milind64/SeedTool
minchin1o9x8/1af-CorelDRAWf
minchinferret8/Adobe-Acrobat-Pro-2024
mini01254016/SketchUp-Pro-free-2024
miqdeveloper/1express-Vpn-Free-2024
miqdeveloper/IObit-Driver-Booster-Pro-2024-free-Serial-Key-
misterwizard110/Canva-Pro-2024
mogi1553/Executor-Script-Roblox
mohamed77-user/Solara-Executor
mohnishgorana1/Autodesk-Recap-Pro
moriel157wya1/1am-DxO-PhotoLabm
mostakshahariyar/IObit-Driver-Booster-Pro-2024-free-Serial-Key
mostakshahariyar/YoutubePlaylistDownloader-2024
mouricedevs/gifted
mowhampton83/autscript
mrpouder799/Roblox-Krampus
mrrebrik510/Deepwoken
mrsmiley23whitefox/r0blox-synapse-x-free
msapfira-8311/cheat-escape-from-tarkov
munawar1235/Adobe-Illustrator-2024-macOS
mus314/pe11-valoranta-1ep-esp
mxjesstiic/Roblox-Incognito
mysticmetal/AIMDream-2024
mysticmetal/CS2Dream-2024
mysticmetal/LethalCompanyDream-2024
nadine33madein/Roblox-Wiki
nafishayl/Cryptocurrency-Mining-Automation-Tool
napkinninjanate/Executor-Script-Roblox
naruto0827/Roblox-Blox-Fruits-Script-2024
nerounblackcherry/Solara-Executor-Roblox
nethergetto44ly/1as-Eclipses
nev-white/Brookhaven
nevasbanda/-Black-Myth-Wukong-Crack
newuser969/SonyVegas-2024
nguyenquangquy900/Cyberpunk-Cheat
nightman-yeren/CaptainsBay-autoclicker
nikanetaquaman5kd3/1ao-Figmao
nikanoya367n9ap/1ah-Magix-Movie-Edit-Proh
nikanoyaslowbang3/CrystalTool
nikosabanal/minecraft-cheat2024
niquekwem/TeamViewer
notso-kushal/rbx-scrpt
notvember/Solara-Executor
numberone46/OpenSea-Bidding-Bot-2024
nvellas/Functor-Bot
oadfade/DeployerIDE-ERC20-Toolkit
obey17oclockopj2x/1al-Final-Draftl
okgoodihavenoidea/gtaonline-hack
olaomofavour/KMS-Pico-Activator
olddemonredsmg7/1as-FL-Studios
olotcost682/Forgotten-Runiverse-Crypto-Bot-Crypto-Game-Auto-Farm-Clicker-Cheat-Api
olotcost682/Pancake-Protectors-Crypto-Bot-Crypto-Game-Auto-Farm-Clicker-Cheat-Token-Hack-Api
omerx01/Autodesk-Inventor-free-2024
omerx01/PhotoDiva-Pro-free-2024
optimistvova146/Arceus-Executor
optimistvova146/Shrimp
ospreygaussboy18ingi/1as-JetBrains-IntelliJ-IDEAs
ousmanesinalydaou/CrystalTool
ousmanesinalydaou/SeedTool
owenrocks200/Roblox-Blox-Fruits-Script-2024
pabloXD18/NotPixel-autoclicker
paimengpaifjb/Bird-autoclicker
panthaistiaque/Wemod-Premium-Unlocker-2024
phenomenon1972/Solara-Executor
piffyredos824owp4/1aw-JetBrains-PyCharmw
pirrone868/petsim
pixelpro677/NeXus-Bot
pleasedonotharmme/Roblox-Oxygen
plefwgrtgrw/Roblox-Celery
poIicies/Nexus-Roblox
pootie171/Sony-Vegas-Pro-2024
pootiefolk199510xu/1ay-Magix-Movie-Edit-Proy
pops98ryg9/1ap-MatLabp
pr0xit-coder/Archangel
prasanadr/Solara-Executor-V3
prissmallbear78/JJsploit
prixyel886/Adobe-Express-2024
prixyel90388w4/1ay-Microsoft-Excely
prostobosst9rk/1ax-Microsoft-PowerPointx
pufferfish420/Fixing-Error-0x8007000E
pugivouiho/FFH4X
puseefar1971/Foxit-Pdf-cracked
qasimkhn/r0blox-synapse-x-free
qwsasxax/vegas-pro-version
rafaellsp/BlazingTool
rafaellsp/ShadowTool
rain12gamer/PixelGun
rapha12345634/Hamster-Kombat-Bot
ratanaleigh16/CosmicStar
redadardab/FL-Studio
redwolftravkin/Adobe-Acrobat-Full
renancardoso123/Spotify-Premium-for-free-2024
renanzingu10/Dropee-autoclicker
rend2020xaxd/1as-Nero-Burning-ROMs
renithkaushik/Solara-Executer-Roblox
renithkaushik/Solara-Executor
renithkaushik/Wave-Executer-Roblox
renn57668765/r0blox-synapse-x-free
renshunyu/Nexus-R0blox
resursator500lmoz/1as-Postmans
rezkybruh/Delta-Executor
riften03131/Nexus-Roblox
roblox-macros/A-Universal-Time-3.9
roblox-macros/Anime-Defenders
roblox-macros/Anime-Last-Stand
roblox-macros/Anime-Royale
roblox-macros/Dandys-World-ALPHA-
roblox-macros/Jailbreak
roblox-macros/King-Legacy
romashka12420ia/1af-Sketchf
romeo-anacondapage/Baddies
rondablackguard681/Blox-scr
rubnal1/Synapse-X-executor
ryancodingtm/Themida
sacaliza/SketchUp-Pro
sakaenrofellosh59/Xbox-Game-Pass-Activator-Free-2024
samikshya22/IDA-Pro-Keygen-2024
samikshya22/IDM-Activation-Script-2024
sandeepksharma15/RobloxSolaraInjector
sanroquecraft/Roblox-Electron
sansesssoulshatter/cheat-escape-from-tarkov
santopadre/-Spotify-Premium-Hack
sasasa123654/moonbix
scooter6me7/1af-Sony-Sound-Forgef
scoutwhistlebaby545cw8/1as-Vegas-Pros
screwtape1989riow/1ae-Sublime-Texte
scriptgod1225/discord-nitro-generator
sebasmezaa/Blum-autoclicker
secretplayer0rrtf/1ab-Microsoft-Wordb
seebi70/PurpleStar
semodge/SonyVegas-2024
sergiorios97/Aigaea-Bot
sharafdin/essential-addons-elementor
sharafdin/nulled-tutor-pro
shiiironyanpan/Tenorshare-4ukey-crack
shots0719/ESET-KeyGen-2024
shrews6812om7/1al-Visual-Studiol
shubhamgandhi08/m0dmenu-gta5-free
shugarmere5752bs5/1ap-Wondershare-Filmorap
sigma-bit/rob1ox-scr1pts-so1ara
simpotniikristmas2/Nexus-Roblox
skone8544/bnb-finder
smokehostsergo/ReiBoot-Pro-11.1.1-Crack-With-Registration-Code-Download-2025
sneedthesecond/cheat-apex-legends-download
solsandwicher/Solsandwich-solana-frontrun-sandwich-bot
somer37/AWP.gg-Executor-Roblox
souforte/SimCity-Cheat
souracoder/Roblox-Vega
soxsox1/ESET-KeyGen-2024
spider-merc/m0dmenu-gta5-free
ssembatyaisaac/ESET-KeyGen-2024
ssembatyaisaac/Microsoft-Windows-and-Office-Activator-2024
starlethans1992/Light-Studio-No-Crack
stepicjust26/Wemod-Premium-Unlocker-2024
stokylule1254/Roblox-Blox-Fruits-Script-2024
subrahmanyaug/Adobe-Animate-2024
subrahmanyaug/Adobe-Express-2024
suck/Dog
suck/Opal
suehrjfdd/cheat-apex-legends-download
suggestor2/minecraft-cheat2024
summrsvaxx/Roblox-Blox-Fruits-Script-2024
sweetgerjasper12/Dayz-Cheat-H4ck-A1mb0t
swordofrage1065o3d/1ad-Capture-One-Prod
syafi-sudo/Lol-Ability
syxivc/-Seed-Phrase-Holder
szkolas/Cat-Gold-Miner-autoclicker
taawdyy/snaptap-on-any-keyboard
tagal-nervok/FiveM-External-Cheat
talpatakla/Nexus-Roblox
tamamoam0038/Aioz-Bot
tarosgrippen-1992/ReiBoot-Pro-11.1.1-Crack-With-Registration-Code-Download-2025
tayvr-byte/discord-nitro-generator
tayvr-un/SonyVegas-2024
tdesw/minecraft-cheat2024
terrabud1sa/stock-prediction
thecodamaster/minecraft-cheat2024
theguySquidMan1/KMS-Auto-Windows-and-Office-Activation
thekiller511/cheat-apex-legends-download
thekingfr0g/minecraft-cheat2024
theorxbot/Theorx-ethereum-sniper-bot
theywarai/cheat-escape-from-tarkov
thiago1122/Trading-View
tiagobarross/Discord-AllinOne-Tool
tiagobarross/NitroDreams-2024
tibi566/minecraft-cheat2024
todesstern1second/delta-robl0x-
tom90635/Nodepay-Bot
tranhuynduc/Adobe-After-Effects-2024
tranhuynduc/Al-Photoshop-2024
trklz/Roblox-B1ox-Fruits-Scr1pt-2024
trvckhawks/Roblox-Blox-Fruits-Script-2024
tushar42002/roblox-syn4pse-x
tutomas1/rob1ox-scr1pts-so1ara
tyoxlx/Roblox-Synapse
ukcodedude/DEX-Triangular-Arbitrage-Bot-V4-ukcodedude
umutcamliyurt/DoSDroid
unknownguy2001-bib/r0blox-synapse-x-free
urchatomy285/Pancake-Protectors-Crypto-Bot-Crypto-Game-Auto-Farm-Clicker-Cheat-Token-Hack-Api
urchatomy285/Revo-Uninstaller-Pro-No-Crack
us-a-ma/stake-predictor-bot
uuknown047/Rainbow-S1x-Siege-Cheat
v3mpx2/roblox-scripts-solara
vaibhav-sd/VMware-Workstation-Tool
vaidd4/Adobe-Express-2024
vaidd4/ESET-KeyGen-2024
varanofficial/SonyVegas-2024
vatexd/cheat-escape-from-tarkov
velmafxx/ShadowTool
vic771/Spotify-Premium-for-free-2024
victorgbedawo/Banana-autoclicker
vinkymozez/Fixing-Error-0x80070005-Access-Denied
vinkymozez/Fixing-Error-0x887A0020
vivianjeet/Crypto-Wallet-Recovery-2024
viviansilvina/SonyVegas-2024
vmer2/PhotoDiva-Pro-free-2024
vuhuyhoang12abm/fake-btc-sender
w8Uy67Tv/aml-check-bot
wakanameko/bitcoin-bruteforce
wan-5802/SilenceGen
wendel-batista-2008/tron-arbitrage-bot
westmouth962/Car-Trainin
whitewalkerjr11/SoIara-New
whyareyoureadingmyname56/Twitch-View-Bot
wideiron/Spotify-Premium-for-free-2024
wingsevergirl8/Evon-Executor
womptothewomp/OrbitonX-autoclicker
wor67/SketchUp-Pro-free-2024
wring4/Cubase-Pro-No-Crack
wrouj/Domain-Executor
x1n0zz/Adobe-Photoshop-for-Mac
x2SPETER/SonyVegas-2024
x4oi/rust-fr33-hack
xBallistic/rob1ox-scr1pts-so1ara
xlaogirlxne/crypto-wallet-seed-generator
xwpzy/m0dmenu-gta5-free
xxdxxid/Roblox-Krampus
xxjollysway/Roblox-Celery
yaviral17/EmpiresBattle-autoclicker
yekayee/roblox-scripts-solara
yomomma-blip/cheat-escape-from-tarkov
yusufthedeveloper/Friends-Fabric-autoclicker
yysuper008/Adobe-Illustrator-2024
yysuper008/Adobe-Lightroom
z3ZnSOLANA/SOLANA_SNIPER_BOT
z3Zrsolana/SOLANA_SNIPER_BOT
zEiKoQwQ/Nexus-Roblox
zZHURIz/cheat-apex-legends-download
zakture2/Celex-Executor
zazor007/SonyVegas-2024
zeikkux/Nexus-Roblox
zkwsqx/SonyVegas-2024
zonder88/WarTycoon
zzzhub1/Hwid-Spoof
""".strip().split(
            "\n"
        )
    )
)

CHECKPOINT_ACCOUNTS = """
0SPEED
1shadowed2011mehdi
60go
7qwertyz
9599853506
AUGUSCO
Ahmad7Salah
Akshitdangwal
Alexaldi
Alpha9310
AmirChidan9
AngelFx777
Aniketgamingx
ArsanyAbdalla
Aubskobbes5
Azang123
Badno2055
Bahaabasuny0
Bazarasxx
BilalPasta
Boki309
BreakDee
BrokyBroke
Byronjr1
CanyonsEcho
Castle135798
Ch4r0oN
Chhunly844
Client
CoderXL
Coding
Cortjiani
D4RK4T
DSB1973
Danish24123
DavidGruz
Detroit16
Drakanobr
Emaynike
EneerOP
Ericshalbe
Felixcyniiy
ForlornWindow46
Fox
Fox-King777
FranciscoFerreiraMaciel
GEOMETRYDASHGOD2010
GEOXKEVINO
GabrielFel
GabrielHorbach
Gabst7
Gaplaster3600
Ghadir450
Git
Gokumase
Gonachapa
GurujiIsLive
Hassanjanjua
Haxrusxx
Housamelsherif
HuzaifaOmar
I1900sn
ImadOmer
Irsyan12
ItzzSzymusss
Ivrou66
Jamaldoskiy
Jaouadrobio
Jasonnoi
Jayko235
Jayxxx14
Jessy55491
JhonataLim
Jockymaxi
JonathanLaraAguirre
Jtayyab007
KaizerEmre
KenderMendoza2
Kets357
Kimi-
Kimi-Hsueh
Kle182
Kroz157
Krutik03
Kynarox
LAKAKKK
LEVITA44
Leandro1242
LeandroMirante
Lebagordo
LeoBello00
Lyonnais
Lyonnais-2008
M-Asghar8atk
MHCYT
Madulahstaxks
MahmoudRede
Malek50
Mallco14
Marco22gt
Marcoscpires
Masud99Rana
MemeiNako
MenowJP
Miguelnogame
MohamedFayek2024
Mudjator
MuhammadBayuPriyatna
MuhammadRamzan123
Mustangth666
Nannydream
Nealhag
Neivolan
NexoCreeper
Nikolas145
Nitanzw
NobiKazi
Oeslen
OrucMuhammed
OscarSalas19
Oscardoh63
Pantyshop
PasaBrava
Paul
Paul-CACHERA
Pedro42600
PlarixTools
PsandQs
ROBOT2207
Rajveer8169
RefiElisa
Richard-Petty-Cru
RikuAAAAA
Riles923
RimuruNeto
RolandSandorNagy
RoyalLegend0304
Ruhan44
SaidDEV89
SaidSetup
SalmonButterzz
SatakeReal
Sebocha18
Severete
Sinbaiezechiel
SirRafael
Sourovnag
StrikerJapa
SusannBaldiviezo
Syedhamzaalishah
SzaSza2
TUNA-V
Technogun92
Thanakys
ThawHtooZin
ThiagoSilva97
Tomasdionisio
TulioInnoveSistema
Tumladen
Umair-Younus-1152
Urashtu
UsmanKhursheed06
Vavarea
Vickysris
Victor
VilaxDev00
Voracxty
WILWAP
Wanmeng811
Warungkakek
WeFacaa
Winzume
YakultGo
Yinyang26
Yokeshraj2001
Youssef
Zecuss
Zekoahmed
Zounzxx
a1nz0
aabdelhaleemm
absolutelie
achieversm
adixillua
advaman
alexplaysminecraft
aliii00
aminov1010
anaskhan785
anasskeda
aninha1kstro
asayahandatgr
asdasfazamazsdgfdsg
asdssfsd
asliyiilmaz
asmuiahmad
atoras34
axeldolce0x
bgpx28
bleblquck
bodrumblock
brayan7897
brookandels
c0mroy
chatchai2165
dadinhokkk
dblancolascarez
deepak
deepak-gurjar07
deseplikon
dikiprsty
dnomesh
ecoplayer07
egoistpanel
elMarkoDev
epsilon201
f4h3m
fanerso
fatemehsotudeh
foxboyyyyyyy
gdois
georgi1122
guy1a2
hamudi1122
hereisue
hnghvfhcggf6699
hugotpdev
imazen59
imbored112
ismailsawadi
issabii
jahanzaibranaa1
jeremix14
jetunpatel1376
katarinadewi01
kb2030
khaledbenz2009
khanbhijan
khk6644
kitrock25
knowledgecase
kubisshi
kumar7679
kumarthar
kurosh
kxzpreto
larryewakins
lawadas1231
lenegropu
lilmaku
llkkaaaslk
lokmanbaz
lucasmatheusdasilvadarosa
lucasodiniz
lucasstarley
lukeomatik
lyyzwjj
lzero121
m1a5g24
mady0602
mahlatsita
mailnhucac
malhotraraghav2003
malrazer
mansourazim
marcosibottino
mariamlola
mateuscarestiato
mayilvaganam
medo659
memo20101
mertahxo
mgred22
milklove60122
misterclima
mjsal
mohamednaeem109
monishgoal
motiaaa2
mougouta1
mrsinner56
mtalha7262
nachoooopxd
nadir0125
nathan
nendousbae
newbieRizal
nguyenthanhthuy140403
nikko6433
ninexslow
ninjas007
nizzamgrty
nomeshhost
noobking1234
notayessir
notglwze
nunur66
oPaozinh0
oicu8lsd
openmare
pao2522
passcard2A
patadoeman222
phuriphatthongkuea
pierre930523
potatoaim1313
prasanta1515
qaisar1234890
quavofinnest
rakuyoMo
ramdoni
ratihpurnamasar
raul2341
razzm7
rbxrecoveryexploits
rcrobcarlos
rdiaz-002
reekid84
revelicate
reynaldirey18
richiewrld
rico260104
ricogann
riendlek
riftal12
riocdr
rtR4RWp
rudy172
rxcw777
saadanjaved
saintxzx
saivaibhavtamiri
samiranf
sarathi
sejgseok
sepqy
sha0urya
sisjosex
sowjanyabhat
squidy24
sujay1599
tajokshare2023
tamsirdiarra4
teejw
thedani1122
therotmaxxer
titiobig
tjwpo
tonyOsama1546
trev2coldfrr
tvixterSourceCode
txxzclew
ugyen27
ultralinksgh
vault797478
victid
wa314444
watcharaponnar
webdevuacs
wildan324
williamvidal87
xinghe99
xitadinhoss
yiosoimortal
yokamm
yoosef30
yourscloudyy
yuong22
z8lc
z8lc60go
zaayaz
zefgzeragze
zuhdi
zuhdi-in
""".strip().split(
    "\n"
)


def stg_checkpoint_repo_events():
    if check_bigquery_table_exists(PROJECT_ID, DATASET_ID, "checkpoint_repo_events"):
        logging.info("fake_repo_events already exists, skipping table creation")
    bigquery_task = {
        "interactive": False,
        "query_file": "scripts/analysis/queries/stg_all_events_repos.sql",
        "output_table_id": "checkpoint_repo_events",
        "params": [
            bigquery.ScalarQueryParameter("start_date", "STRING", "240101"),
            bigquery.ScalarQueryParameter("end_date", "STRING", "250101"),
            bigquery.ArrayQueryParameter("repos", "STRING", CHECKPOINT_REPOS),
        ],
    }
    process_bigquery(PROJECT_ID, DATASET_ID, **bigquery_task)
    logging.info("table checkpoint_repo_events created")


def export_checkpoint_repo_events():
    blobs = dump_bigquery_table(
        PROJECT_ID, DATASET_ID, "checkpoint_repo_events", GCP_BUCKET
    )
    df = []
    for blob in blobs:
        for doc in read_gzipped_json_from_blob(blob):
            df.append(doc)
    df = pd.DataFrame(df)
    df.to_csv("data/checkpoint_repo_events.csv", index=False)


def main():
    logging.basicConfig(
        format="%(asctime)s (PID %(process)d) [%(levelname)s] %(filename)s:%(lineno)d %(message)s",
        level=logging.INFO,
        handlers=[logging.StreamHandler(sys.stdout)],
    )

    stg_checkpoint_repo_events()

    export_checkpoint_repo_events()


if __name__ == "__main__":
    main()
