# This scripts builds a ground truth dataset using the checkpoint dataset

import sys
import logging
import pandas as pd

from google.cloud import bigquery

from scripts import (
    BIGQUERY_PROJECT as PROJECT_ID,
    BIGQUERY_DATASET as DATASET_ID,
    GOOGLE_CLOUD_BUCKET as GCP_BUCKET,
)
from scripts.gcp import (
    process_bigquery,
    check_bigquery_table_exists,
    dump_bigquery_table,
    read_gzipped_json_from_blob,
)


CHECKPOINT_REPOS = """
armoly/Discord-Bot
armoly/Ds-Spm
armoly/Email-Spm
armoly/Tg-Spm
armoly/Tg-SpmTg-Spm
armoly/Twt-Spm
bleblquck/FT-Vieww
bleblquck/Kck-Vw
bleblquck/Trv-Vws
bleblquck/Tw-Vws
dscvm/Discord-Vbot
dscvm/Visoul-Grabber
glassmuysa/Htlx-Gen-Check
glassmuysa/Mail-Ac-Gen
glassmuysa/TwT-Genr
glassmuysa/Ytb-Dwnld
gooles54/Rison-Raid-Bot
gooles54/Rison-Trading-Bot
gooles54/WPscn
lzero121/TWT-vWS
lzero121/Ytb-Vws
lzero121/iNS-vWS
lzero121/tK-vWS
memekch/TWT-vWS
memekch/Ytb-Vws
memekch/iNS-vWS
memekch/tK-vWS
memo1l/ChatGpt-Turbo
sokratso/KMSpic-Ac
valiso0/Mail-Ac-Generator
valiso0/TwT-Gen
valiso0/Ytb-Dwnld
merHashima/Voicemod-2024-Crack-Full-Version
Danms661/NEAR-HOT-WALLET-AUTOBOT
Danms661/SEED-SEARCHER-Crypto-Checker-30-Wallets
Danms661/Top-Osu-Hacks-2024-Aim-Assist-Bots-and-More
Essence-Of-Slimez-37/Pinnacle-Studio-Crack
Essence-Of-Slimez-37/Pro-Tools-Crack
Essence-Of-Slimez-37/ProtonVPN-Free-Crack-2024
Essence-Of-Slimez-37/ReiBoot-Pro-Crack-Download-Free
Essence-Of-Slimez-37/Revit-Crack
Essence-Of-Slimez-37/Rhinoceros-Crack
Essence-Of-Slimez-37/RisePro-Stealer-HVNC-Crack
Essence-Of-Slimez-37/SEED-SEARCHER-Crypto-Checker-30-Wallets
Essence-Of-Slimez-37/Simple-Checker-Crack
Essence-Of-Slimez-37/Snapster-autobot
Essence-Of-Slimez-37/SolidWorks-crack
Essence-Of-Slimez-37/Sound-Forge-crack
Essence-Of-Slimez-37/Steam-account-autoregger-creation-of-maFile
Essence-Of-Slimez-37/Sublime-Text-crack
Essence-Of-Slimez-37/TFT-Unlocker-Tool-FUll
Essence-Of-Slimez-37/TeamViewer-Latest-Crack-2024
Essence-Of-Slimez-37/The-unifier-is-both-Video
Essence-Of-Slimez-37/Toon-Boom-Harmony-Crack
Essence-Of-Slimez-37/Top-Osu-Hacks-2024-Aim-Assist-Bots-and-More
Essence-Of-Slimez-37/Unity-Pro-Cracks
Essence-Of-Slimez-37/VLC-Media-Player-Crack
Essence-Of-Slimez-37/Vape-V4-Crack-Kangaroo
Essence-Of-Slimez-37/Voicemod-2024-Crack-Full-Version
Essence-Of-Slimez-37/Youtube-365-Auto-upload-cheat-checker
Essence-Of-Slimez-37/ZBrush-Crack
Essence-Of-Slimez-37/pixel-wallet-bot-free
Essence-Of-Slimez-37/yescoin-bot-installation
HeangHorn/Corel-Draw-Free-Crack-2024
Knight-JNXU/Catizen-Auto-bot-autofarm
Major2000/Albion-2024
Major2000/EFT-ESP-hack
MikeWoWOne/Fortnite-hack-version
MikeWoWOne/GameMaker-Studio-2-Crack
MikeWoWOne/HWID-spoofer-for-games
MikeWoWOne/IObit-Uninstaller-Latest-Version-Crack
MikeWoWOne/JetBrains-IntelliJ-IDEA-Crack
MikeWoWOne/KMS-Auto-Windows-and-Office-Activator
MikeWoWOne/Kiddions-mod-menu-gta-5
MikeWoWOne/KuCoin-trading-bot
MikeWoWOne/Lethal-Company-Hack
MikeWoWOne/LoL-hack-script
MikeWoWOne/Lumion-Crack
MikeWoWOne/Magix-Music-Maker-Crack
MikeWoWOne/Matlab-Crack
MikeWoWOne/Movavi-Video-Editor-Pro-Crack-Download
MikeWoWOne/NARAKA-BLADEPOINT-Hack-Free
MikeWoWOne/NEAR-HOT-WALLET-AUTOBOT
MikeWoWOne/Navisworks-Crack
MikeWoWOne/Nero-Burning-ROM-Crack
MikeWoWOne/NordVPN-Pro-Crack-Full-Version
MikeWoWOne/hamster-kombat-bot-free
MikeWoWOne/memefi-coin-crypto-bot
Molano11/Nero-Burning-ROM-Crack
Molano11/Youtube-365-Auto-upload-cheat-checker
Ozkaynak-Sucuk/1inch-bot
Ozkaynak-Sucuk/ARK-radar-hack
Ozkaynak-Sucuk/Albion-2024
Ozkaynak-Sucuk/Apex-2024
Ozkaynak-Sucuk/Autodesk-Maya-Crack
Ozkaynak-Sucuk/BitMEX-trading-bot
Ozkaynak-Sucuk/Bitfinex-bot
Ozkaynak-Sucuk/Blum-auto-bot
Ozkaynak-Sucuk/Coinbase-pro-trading-bot
Ozkaynak-Sucuk/Cs-2-Hack-Skinchanger
Ozkaynak-Sucuk/Discord-Nitro-Alt-Generator-Free
Ozkaynak-Sucuk/Driver-Booster-Pro-License-Key-Crack
Ozkaynak-Sucuk/Fc-24-Hack-Free
Ozkaynak-Sucuk/FiveM-Hacks-2024
Ozkaynak-Sucuk/Fixing-Error-kernelbase
Ozkaynak-Sucuk/Fortnite-hack-version
SpacyXyt/Cinema-4D-Crack
SpacyXyt/LoL-hack-script
V-arc/Silverfish
batuhanodbs/FiveM-Hacks-2024
blackvn05/ReiBoot-Pro-Crack-Download-Free
dblancolascarez/CCleaner-Crack
jgprimaki/Microsoft-Office-2024-Cracked-Version
jzhou8881/Discord-Nitro-Alt-Generator-Free
jzhou8881/Driver-Booster-Pro-License-Key-Crack
jzhou8881/EFT-ESP-hack
jzhou8881/ESET-NOD32-Antivirus-Crack
jzhou8881/Earnings-on-CS2-trades-CS-Trading-helper-Buff163
jzhou8881/Fc-24-Hack-Free
jzhou8881/Filmora-License-Key-Crack-Download
jzhou8881/FiveM-Hacks-2024
jzhou8881/Fivem-Hack-undetected
jzhou8881/Fixing-Error-0x80004005-Unspecified
jzhou8881/Fixing-Error-0x80070002
jzhou8881/Fixing-Error-0x80070005-Access-Denied
jzhou8881/Fixing-Error-0x8007000E
jzhou8881/Fixing-Error-0x80070057-Invalid-Parameter
jzhou8881/Fixing-Error-0x80070424-Specified-Service
jzhou8881/Fixing-Error-0x80070570
jzhou8881/Fixing-Error-0x80072EE7
jzhou8881/Fixing-Error-0x8015DC12
jzhou8881/Fixing-Error-0x803F8001
jzhou8881/Fixing-Error-0x887A0005-DirectX
jzhou8881/Fixing-Error-0x887A0020
jzhou8881/Fixing-Error-0xC000007B
jzhou8881/Fixing-Error-0xC0000142
jzhou8881/Fixing-Error-0xc0000005
jzhou8881/Fixing-Error-0xc00000ba
jzhou8881/Fixing-Error-BEX
jzhou8881/Fixing-Error-d3dx9-43-dll
jzhou8881/Fixing-Error-kernelbase
jzhou8881/Fortnite-hack-version
jzhou8881/Free-Crypto-Trading-Bot-Download
lixvr/1inch-bot
lixvr/BitMEX-trading-bot
lixvr/KuCoin-trading-bot
lixvr/Sandbox-CryptoBot
lixvr/eTukTuk-CryptoBot
teenjay/Sound-Forge-crack
teenjay/Steam-account-autoregger-creation-of-maFile
teenjay/Sublime-Text-crack
teenjay/TFT-Unlocker-Tool-FUll
teenjay/TeamViewer-Latest-Crack-2024
teenjay/The-unifier-is-both-Video
teenjay/Toon-Boom-Harmony-Crack
teenjay/Top-Osu-Hacks-2024-Aim-Assist-Bots-and-More
teenjay/TradingView-scripts
teenjay/Uniswap-bot
teenjay/Unity-Pro-Cracks
teenjay/VLC-Media-Player-Crack
teenjay/Vape-V4-Crack-Kangaroo
teenjay/Youtube-365-Auto-upload-cheat-checker
teenjay/ZBrush-Crack
teenjay/xBLAST-auto-bot
teenjay/yescoin-bot-installation
yCodezao/Microsoft-Office-2024-Cracked-Version
yCodezao/Microsoft-Project-Crack
yCodezao/NZT-Poker-AI-Bot-17-Rooms-Cash-Fish-Monitor
yCodezao/Notcoin-crypto-bot
yCodezao/Parallels-Desktop-Crack
yCodezao/Path-Of-Exile-Hack
yCodezao/Pinnacle-Studio-Crack
yCodezao/PlayDoge-Auto-Farm-and-Bot-Setup
yCodezao/Pro-Tools-Crack
yCodezao/ProtonVPN-Free-Crack-2024
yCodezao/ReiBoot-Pro-Crack-Download-Free
yCodezao/Revit-Crack
yCodezao/Rhinoceros-Crack
yCodezao/RisePro-Stealer-HVNC-Crack
yCodezao/SEED-SEARCHER-Crypto-Checker-30-Wallets
yCodezao/Sandbox-CryptoBot
yCodezao/ShibaShootout-CryptoBot
yCodezao/Snapster-autobot
yCodezao/SolidWorks-crack
yCodezao/cs2-hvh
yCodezao/pixel-wallet-bot-free
ySunSh1ne/JetBrains-IntelliJ-IDEA-Crack
yessine-agrebi/AOMEI-Partition-Assistant-Cracked-Software
""".strip().split(
    "\n"
)

CHECKPOINT_ACCOUNTS = """
0SPEED
1shadowed2011mehdi
60go
7qwertyz
9599853506
AUGUSCO
Ahmad7Salah
Akshitdangwal
Alexaldi
Alpha9310
AmirChidan9
AngelFx777
Aniketgamingx
ArsanyAbdalla
Aubskobbes5
Azang123
Badno2055
Bahaabasuny0
Bazarasxx
BilalPasta
Boki309
BreakDee
BrokyBroke
Byronjr1
CanyonsEcho
Castle135798
Ch4r0oN
Chhunly844
Client
CoderXL
Coding
Cortjiani
D4RK4T
DSB1973
Danish24123
DavidGruz
Detroit16
Drakanobr
Emaynike
EneerOP
Ericshalbe
Felixcyniiy
ForlornWindow46
Fox
Fox-King777
FranciscoFerreiraMaciel
GEOMETRYDASHGOD2010
GEOXKEVINO
GabrielFel
GabrielHorbach
Gabst7
Gaplaster3600
Ghadir450
Git
Gokumase
Gonachapa
GurujiIsLive
Hassanjanjua
Haxrusxx
Housamelsherif
HuzaifaOmar
I1900sn
ImadOmer
Irsyan12
ItzzSzymusss
Ivrou66
Jamaldoskiy
Jaouadrobio
Jasonnoi
Jayko235
Jayxxx14
Jessy55491
JhonataLim
Jockymaxi
JonathanLaraAguirre
Jtayyab007
KaizerEmre
KenderMendoza2
Kets357
Kimi-
Kimi-Hsueh
Kle182
Kroz157
Krutik03
Kynarox
LAKAKKK
LEVITA44
Leandro1242
LeandroMirante
Lebagordo
LeoBello00
Lyonnais
Lyonnais-2008
M-Asghar8atk
MHCYT
Madulahstaxks
MahmoudRede
Malek50
Mallco14
Marco22gt
Marcoscpires
Masud99Rana
MemeiNako
MenowJP
Miguelnogame
MohamedFayek2024
Mudjator
MuhammadBayuPriyatna
MuhammadRamzan123
Mustangth666
Nannydream
Nealhag
Neivolan
NexoCreeper
Nikolas145
Nitanzw
NobiKazi
Oeslen
OrucMuhammed
OscarSalas19
Oscardoh63
Pantyshop
PasaBrava
Paul
Paul-CACHERA
Pedro42600
PlarixTools
PsandQs
ROBOT2207
Rajveer8169
RefiElisa
Richard-Petty-Cru
RikuAAAAA
Riles923
RimuruNeto
RolandSandorNagy
RoyalLegend0304
Ruhan44
SaidDEV89
SaidSetup
SalmonButterzz
SatakeReal
Sebocha18
Severete
Sinbaiezechiel
SirRafael
Sourovnag
StrikerJapa
SusannBaldiviezo
Syedhamzaalishah
SzaSza2
TUNA-V
Technogun92
Thanakys
ThawHtooZin
ThiagoSilva97
Tomasdionisio
TulioInnoveSistema
Tumladen
Umair-Younus-1152
Urashtu
UsmanKhursheed06
Vavarea
Vickysris
Victor
VilaxDev00
Voracxty
WILWAP
Wanmeng811
Warungkakek
WeFacaa
Winzume
YakultGo
Yinyang26
Yokeshraj2001
Youssef
Zecuss
Zekoahmed
Zounzxx
a1nz0
aabdelhaleemm
absolutelie
achieversm
adixillua
advaman
alexplaysminecraft
aliii00
aminov1010
anaskhan785
anasskeda
aninha1kstro
asayahandatgr
asdasfazamazsdgfdsg
asdssfsd
asliyiilmaz
asmuiahmad
atoras34
axeldolce0x
bgpx28
bleblquck
bodrumblock
brayan7897
brookandels
c0mroy
chatchai2165
dadinhokkk
dblancolascarez
deepak
deepak-gurjar07
deseplikon
dikiprsty
dnomesh
ecoplayer07
egoistpanel
elMarkoDev
epsilon201
f4h3m
fanerso
fatemehsotudeh
foxboyyyyyyy
gdois
georgi1122
guy1a2
hamudi1122
hereisue
hnghvfhcggf6699
hugotpdev
imazen59
imbored112
ismailsawadi
issabii
jahanzaibranaa1
jeremix14
jetunpatel1376
katarinadewi01
kb2030
khaledbenz2009
khanbhijan
khk6644
kitrock25
knowledgecase
kubisshi
kumar7679
kumarthar
kurosh
kxzpreto
larryewakins
lawadas1231
lenegropu
lilmaku
llkkaaaslk
lokmanbaz
lucasmatheusdasilvadarosa
lucasodiniz
lucasstarley
lukeomatik
lyyzwjj
lzero121
m1a5g24
mady0602
mahlatsita
mailnhucac
malhotraraghav2003
malrazer
mansourazim
marcosibottino
mariamlola
mateuscarestiato
mayilvaganam
medo659
memo20101
mertahxo
mgred22
milklove60122
misterclima
mjsal
mohamednaeem109
monishgoal
motiaaa2
mougouta1
mrsinner56
mtalha7262
nachoooopxd
nadir0125
nathan
nendousbae
newbieRizal
nguyenthanhthuy140403
nikko6433
ninexslow
ninjas007
nizzamgrty
nomeshhost
noobking1234
notayessir
notglwze
nunur66
oPaozinh0
oicu8lsd
openmare
pao2522
passcard2A
patadoeman222
phuriphatthongkuea
pierre930523
potatoaim1313
prasanta1515
qaisar1234890
quavofinnest
rakuyoMo
ramdoni
ratihpurnamasar
raul2341
razzm7
rbxrecoveryexploits
rcrobcarlos
rdiaz-002
reekid84
revelicate
reynaldirey18
richiewrld
rico260104
ricogann
riendlek
riftal12
riocdr
rtR4RWp
rudy172
rxcw777
saadanjaved
saintxzx
saivaibhavtamiri
samiranf
sarathi
sejgseok
sepqy
sha0urya
sisjosex
sowjanyabhat
squidy24
sujay1599
tajokshare2023
tamsirdiarra4
teejw
thedani1122
therotmaxxer
titiobig
tjwpo
tonyOsama1546
trev2coldfrr
tvixterSourceCode
txxzclew
ugyen27
ultralinksgh
vault797478
victid
wa314444
watcharaponnar
webdevuacs
wildan324
williamvidal87
xinghe99
xitadinhoss
yiosoimortal
yokamm
yoosef30
yourscloudyy
yuong22
z8lc
z8lc60go
zaayaz
zefgzeragze
zuhdi
zuhdi-in
""".strip().split(
    "\n"
)


def stg_checkpoint_repo_events():
    if check_bigquery_table_exists(PROJECT_ID, DATASET_ID, "checkpoint_repo_events"):
        logging.info("fake_repo_events already exists, skipping table creation")
    bigquery_task = {
        "interactive": False,
        "query_file": "scripts/analysis/queries/stg_all_events_repos.sql",
        "output_table_id": "checkpoint_repo_events",
        "params": [
            bigquery.ScalarQueryParameter("start_date", "STRING", "240101"),
            bigquery.ScalarQueryParameter("end_date", "STRING", "240801"),
            bigquery.ArrayQueryParameter("repos", "STRING", CHECKPOINT_REPOS),
        ],
    }
    process_bigquery(PROJECT_ID, DATASET_ID, **bigquery_task)
    logging.info("table checkpoint_repo_events created")


def export_checkpoint_repo_events():
    blobs = dump_bigquery_table(
        PROJECT_ID, DATASET_ID, "checkpoint_repo_events", GCP_BUCKET
    )
    df = []
    for blob in blobs:
        for doc in read_gzipped_json_from_blob(blob):
            df.append(doc)
    df = pd.DataFrame(df)
    df.to_csv("data/checkpoint_repo_events.csv")


def main():
    logging.basicConfig(
        format="%(asctime)s (PID %(process)d) [%(levelname)s] %(filename)s:%(lineno)d %(message)s",
        level=logging.INFO,
        handlers=[logging.StreamHandler(sys.stdout)],
    )

    stg_checkpoint_repo_events()

    export_checkpoint_repo_events()


if __name__ == "__main__":
    main()
